export const TEST_TOURNAMENTS = [
  {
    id: "1",
    court: {
      courtId: 1,
      courtName: "PowerPadel",
      location: "123 Main St, Dallas, TX",
      owner: {
        userId: 1,
        firstName: "John",
        lastName: "Owner",
      },
    },
    tournamentName: "Dallas Open",
    date: "2024-01-15",
    registrationFee: "10",
    reward: "50",
    playerLevel: "Amateur",
    isOpen: true,
  },
  {
    id: "2",
    court: {
      courtId: 2,
      courtName: "Grand Slam Courts",
      location: "456 Elm St, Austin, TX",
      owner: {
        userId: 2,
        firstName: "Mike",
        lastName: "Johnson",
      },
    },
    tournamentName: "Austin Classic",
    date: "2024-02-05",
    registrationFee: "15",
    reward: "75",
    playerLevel: "Intermediate",
    isOpen: true,
  },
  {
    id: "3",
    court: {
      courtId: 3,
      courtName: "Padel Supreme",
      location: "789 Oak Rd, Miami, FL",
      owner: {
        userId: 3,
        firstName: "Emily",
        lastName: "Smith",
      },
    },
    tournamentName: "Miami Smash",
    date: "2024-01-20",
    registrationFee: "20",
    reward: "100",
    playerLevel: "Advanced",
    isOpen: true,
  },
  {
    id: "4",
    court: {
      courtId: 4,
      courtName: "Victory Courts",
      location: "321 Pine St, Chicago, IL",
      owner: {
        userId: 4,
        firstName: "Sarah",
        lastName: "Williams",
      },
    },
    tournamentName: "Chicago Invitational",
    date: "2024-02-10",
    registrationFee: "12",
    reward: "60",
    playerLevel: "Amateur",
    isOpen: true,
  },
  {
    id: "5",
    court: {
      courtId: 5,
      courtName: "Ace Arena",
      location: "678 Birch St, Orlando, FL",
      owner: {
        userId: 5,
        firstName: "David",
        lastName: "Brown",
      },
    },
    tournamentName: "Orlando Slam",
    date: "2024-03-01",
    registrationFee: "25",
    reward: "125",
    playerLevel: "Pro",
    isOpen: true,
  },
  {
    id: "6",
    court: {
      courtId: 6,
      courtName: "Prime Padel",
      location: "123 Lakeview Dr, Denver, CO",
      owner: {
        userId: 6,
        firstName: "Ashley",
        lastName: "Garcia",
      },
    },
    tournamentName: "Denver Duo",
    date: "2024-01-25",
    registrationFee: "18",
    reward: "90",
    playerLevel: "Intermediate",
    isOpen: true,
  },
  {
    id: "7",
    court: {
      courtId: 7,
      courtName: "Rally Rackets",
      location: "555 Maple Ave, San Diego, CA",
      owner: {
        userId: 7,
        firstName: "Brian",
        lastName: "Davis",
      },
    },
    tournamentName: "San Diego Rumble",
    date: "2024-02-18",
    registrationFee: "10",
    reward: "50",
    playerLevel: "Amateur",
    isOpen: true,
  },
  {
    id: "8",
    court: {
      courtId: 8,
      courtName: "Smash Zone",
      location: "111 Cedar Dr, Las Vegas, NV",
      owner: {
        userId: 8,
        firstName: "Laura",
        lastName: "Martinez",
      },
    },
    tournamentName: "Vegas Smashdown",
    date: "2024-03-10",
    registrationFee: "30",
    reward: "150",
    playerLevel: "Advanced",
    isOpen: true,
  },
  {
    id: "9",
    court: {
      courtId: 9,
      courtName: "Court Kings",
      location: "222 Ash St, Seattle, WA",
      owner: {
        userId: 9,
        firstName: "Chris",
        lastName: "Wilson",
      },
    },
    tournamentName: "Seattle Showdown",
    date: "2024-02-22",
    registrationFee: "20",
    reward: "100",
    playerLevel: "Intermediate",
    isOpen: true,
  },
  {
    id: "10",
    court: {
      courtId: 10,
      courtName: "TopSpin Courts",
      location: "777 Cypress St, Phoenix, AZ",
      owner: {
        userId: 10,
        firstName: "Megan",
        lastName: "Anderson",
      },
    },
    tournamentName: "Phoenix Heat",
    date: "2024-01-28",
    registrationFee: "25",
    reward: "120",
    playerLevel: "Advanced",
    isOpen: true,
  },
  {
    id: "11",
    court: {
      courtId: 11,
      courtName: "Baseline Arena",
      location: "432 Spruce Rd, Nashville, TN",
      owner: {
        userId: 11,
        firstName: "Andrew",
        lastName: "Clark",
      },
    },
    tournamentName: "Nashville Open",
    date: "2024-03-15",
    registrationFee: "15",
    reward: "75",
    playerLevel: "Intermediate",
    isOpen: true,
  },
  {
    id: "12",
    court: {
      courtId: 12,
      courtName: "GamePoint Courts",
      location: "900 Redwood Blvd, Portland, OR",
      owner: {
        userId: 12,
        firstName: "Rachel",
        lastName: "Adams",
      },
    },
    tournamentName: "Portland Classic",
    date: "2024-02-15",
    registrationFee: "20",
    reward: "80",
    playerLevel: "Intermediate",
    isOpen: true,
  },
  {
    id: "13",
    court: {
      courtId: 13,
      courtName: "Skyline Courts",
      location: "300 Summit Blvd, New York, NY",
      owner: {
        userId: 13,
        firstName: "Steven",
        lastName: "Perez",
      },
    },
    tournamentName: "NY Skyline Smash",
    date: "2024-03-20",
    registrationFee: "30",
    reward: "150",
    playerLevel: "Pro",
    isOpen: true,
  },
  {
    id: "14",
    court: {
      courtId: 14,
      courtName: "Courtside Elite",
      location: "850 Golden Rd, San Francisco, CA",
      owner: {
        userId: 14,
        firstName: "Olivia",
        lastName: "Miller",
      },
    },
    tournamentName: "Golden Gate Challenge",
    date: "2024-02-28",
    registrationFee: "15",
    reward: "85",
    playerLevel: "Intermediate",
    isOpen: true,
  },
  {
    id: "15",
    court: {
      courtId: 15,
      courtName: "Smash Circuit",
      location: "110 Harbor Ave, Los Angeles, CA",
      owner: {
        userId: 15,
        firstName: "Ethan",
        lastName: "Rodriguez",
      },
    },
    tournamentName: "LA Showstopper",
    date: "2024-03-25",
    registrationFee: "25",
    reward: "130",
    playerLevel: "Advanced",
    isOpen: true,
  },
  {
    id: "16",
    court: {
      courtId: 16,
      courtName: "Precision Courts",
      location: "555 Walnut St, Charlotte, NC",
      owner: {
        userId: 16,
        firstName: "Sophia",
        lastName: "Walker",
      },
    },
    tournamentName: "Charlotte Clash",
    date: "2024-03-05",
    registrationFee: "10",
    reward: "50",
    playerLevel: "Amateur",
    isOpen: false,
  },
  {
    id: "17",
    court: {
      courtId: 17,
      courtName: "Epic Rallies",
      location: "789 Willow Ln, Houston, TX",
      owner: {
        userId: 17,
        firstName: "Liam",
        lastName: "Young",
      },
    },
    tournamentName: "Houston Heatwave",
    date: "2024-04-01",
    registrationFee: "20",
    reward: "100",
    playerLevel: "Intermediate",
    isOpen: false,
  },
  {
    id: "18",
    court: {
      courtId: 18,
      courtName: "Net Masters",
      location: "203 Cypress Ln, Atlanta, GA",
      owner: {
        userId: 18,
        firstName: "Alexander",
        lastName: "White",
      },
    },
    tournamentName: "Atlanta Grand",
    date: "2024-03-12",
    registrationFee: "30",
    reward: "150",
    playerLevel: "Pro",
    isOpen: false,
  },
  {
    id: "19",
    court: {
      courtId: 19,
      courtName: "Smash Masters",
      location: "444 Cherry Blvd, Tampa, FL",
      owner: {
        userId: 19,
        firstName: "Isabella",
        lastName: "Hall",
      },
    },
    tournamentName: "Tampa Bay Smash",
    date: "2024-02-25",
    registrationFee: "15",
    reward: "75",
    playerLevel: "Intermediate",
    isOpen: false,
  },
  {
    id: "20",
    court: {
      courtId: 20,
      courtName: "BreakPoint Arena",
      location: "333 Spruce St, Philadelphia, PA",
      owner: {
        userId: 20,
        firstName: "James",
        lastName: "Moore",
      },
    },
    tournamentName: "Philly Open",
    date: "2024-04-10",
    registrationFee: "10",
    reward: "50",
    playerLevel: "Amateur",
    isOpen: false,
  },
];
