/**
 * This file was largely generated by ChatGPT.
 */

import React, { createContext, useState, useContext } from "react";

const UserContext = createContext();

export const useUser = () => useContext(UserContext);

export const UserProvider = ({ children }) => {
  const [user, setUserState] = useState(null);

  // Custom setUser function that updates both state and localStorage
  const setUser = (userData) => {
    if (userData) {
      localStorage.setItem("user", JSON.stringify(userData)); // Save user data to localStorage
    } else {
      localStorage.removeItem("user"); // Clear localStorage if no user data
    }
    setUserState(userData); // Update React state
  };

  return (
    <UserContext.Provider value={{ user, setUser }}>
      {children}
    </UserContext.Provider>
  );
};
